### ISSUE TITLE
ModuleNotFoundError: No module named 'thriftpy2.transport.buffered.cybuffered'

### ISSUE THREAD

**Issue by better319** [zvtvz/zvt#103]
这个模块经常换台电脑安装就报错，也不知道怎么会事情。

> from zvt import 

就报错了

`

3.7.6
pip3 install thriftpy2-0.4.11-py3-none-any.whl
还是报这个错，求指点，谢谢！！

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-005d93f24027> in <module>
----> 1 from zvt import *

/opt/conda/lib/python3.7/site-packages/zvt/__init__.py in <module>
    111 
    112 import zvt.domain as domain
--> 113 import zvt.recorders as recorders
    114 
    115 import pluggy

/opt/conda/lib/python3.7/site-packages/zvt/recorders/__init__.py in <module>
      1 # -*- coding: utf-8 -*-
----> 2 from zvt.recorders.eastmoney import *
      3 from zvt.recorders.exchange import *
      4 from zvt.recorders.joinquant import *
      5 from zvt.recorders.sina import *

/opt/conda/lib/python3.7/site-packages/zvt/recorders/eastmoney/__init__.py in <module>
      1 # -*- coding: utf-8 -*-
      2 from zvt.recorders.eastmoney.dividend_financing import *
----> 3 from zvt.recorders.eastmoney.finance import *
      4 from zvt.recorders.eastmoney.holder import *
      5 from zvt.recorders.eastmoney.meta import *

/opt/conda/lib/python3.7/site-packages/zvt/recorders/eastmoney/finance/__init__.py in <module>
      1 # -*- coding: utf-8 -*-
----> 2 from zvt.recorders.eastmoney.finance.china_stock_balance_sheet_recorder import *
      3 from zvt.recorders.eastmoney.finance.china_stock_cash_flow_recorder import *
      4 from zvt.recorders.eastmoney.finance.china_stock_finance_factor_recorder import *
      5 from zvt.recorders.eastmoney.finance.china_stock_income_statement_recorder import *

/opt/conda/lib/python3.7/site-packages/zvt/recorders/eastmoney/finance/china_stock_balance_sheet_recorder.py in <module>
      4 from zvt.api.quote import to_report_period_type
      5 from zvt.domain import BalanceSheet
----> 6 from zvt.recorders.eastmoney.finance.base_china_stock_finance_recorder import BaseChinaStockFinanceRecorder
      7 
      8 balance_sheet_map = {

/opt/conda/lib/python3.7/site-packages/zvt/recorders/eastmoney/finance/base_china_stock_finance_recorder.py in <module>
      1 # -*- coding: utf-8 -*-
      2 import pandas as pd
----> 3 from jqdatasdk import auth, query, indicator, get_fundamentals, logout
      4 
      5 from zvt import zvt_env

/opt/conda/lib/python3.7/site-packages/jqdatasdk/__init__.py in <module>
      4 sys.modules["ROOT_DIR"] = os.path.abspath(os.path.dirname(__file__))
      5 
----> 6 from .api import *
      7 from .finance_service import *
      8 from . import alpha101

/opt/conda/lib/python3.7/site-packages/jqdatasdk/api.py in <module>
      4 import requests
      5 from .utils import *
----> 6 from .client import JQDataClient
      7 
      8 @assert_auth

/opt/conda/lib/python3.7/site-packages/jqdatasdk/client.py in <module>
     12 import thriftpy2 as thriftpy
     13 from pandas.compat import pickle_compat as pc
---> 14 from thriftpy2 import transport, protocol
     15 if platform.system().lower() != "windows":
     16     socket_error = (transport.TTransportException, socket.error, protocol.cybin.ProtocolError)

/opt/conda/lib/python3.7/site-packages/thriftpy2/transport/__init__.py in <module>
      9 from .sslsocket import TSSLSocket, TSSLServerSocket
     10 from ._ssl import create_thriftpy_context
---> 11 from .buffered import TBufferedTransport, TBufferedTransportFactory
     12 from .framed import TFramedTransport, TFramedTransportFactory
     13 from .memory import TMemoryBuffer

/opt/conda/lib/python3.7/site-packages/thriftpy2/transport/buffered/__init__.py in <module>
     66 
     67 if CYTHON:
---> 68     from .cybuffered import TCyBufferedTransport, TCyBufferedTransportFactory  # noqa

ModuleNotFoundError: No module named 'thriftpy2.transport.buffered.cybuffered'

`

**Comment by better319** [comment]
![1](https://user-images.githubusercontent.com/13842581/91144714-02618200-e6e7-11ea-80e5-6d8010e36f77.png)

![2](https://user-images.githubusercontent.com/13842581/91144722-04c3dc00-e6e7-11ea-96bc-36352c8017e6.png)

**Comment by better319** [comment]
![1](https://user-images.githubusercontent.com/13842581/91144849-29b84f00-e6e7-11ea-817a-2f167db641d7.png)
![2](https://user-images.githubusercontent.com/13842581/91144858-2b821280-e6e7-11ea-8f9e-e88d19059590.png)

**Comment by better319** [comment]
https://download.lfd.uci.edu/pythonlibs/w3jqiv8s/thriftpy2-0.4.11-py3-none-any.whl

**Comment by foolcage** [comment]
看起来是JQDataClient的问题。。

**Comment by better319** [comment]
conda install thriftpy2   这样就解决了

**Comment by better319** [comment]
不能用pip
pip那个库好像有问题，表面好像是装好了，实际还是有问题
