### ISSUE TITLE
推荐加一个筛股方案

### ISSUE THREAD

**Issue by Mr-later** [zvtvz/zvt#106]
股票推荐研报列表
  要求研发发布时间为最近两天
  要求研报数量大于6
  要求推荐买入或者增持
  要求有行业专家推荐（同花顺里有，如图，不知道其他有没有这个）
  推荐成功率大于75%的推荐清单里有（同花顺里有个研究员推荐成功率排名）
![image](https://user-images.githubusercontent.com/24469848/91923648-70b7cd00-ed03-11ea-9040-7e1981df88f6.png)
![image](https://user-images.githubusercontent.com/24469848/91923697-8dec9b80-ed03-11ea-9ad8-3aead79e4ea2.png)

查询返回股票编号，研报列表，推荐成功率，及对应研究员

你们看看这个方案可行嘛？或者有什么优化，我自己是这样选的，成功率还可以，也有大概75%-80%的成功率

**Comment by foolcage** [comment]
考虑加入这个数据，属于ActorEntity的一部分
