### ISSUE TITLE
AttributeError: module 'zvt' has no attribute 'AdjustType'

### ISSUE THREAD

**Issue by tedzzx** [zvtvz/zvt#129]
在快速开始中出现error, 谢谢。

In [1]: import os
In [2]: os.environ["TESTING_ZVT"] = "1"
In [3]: from zvt import *
{'data_path': 'C:\\Users\\trade\\zvt-test-home\\data',
 'log_path': 'C:\\Users\\trade\\zvt-test-home\\logs',
 'tmp_path': 'C:\\Users\\trade\\zvt-test-home\\tmp',
 'ui_path': 'C:\\Users\\trade\\zvt-test-home\\ui',
 'zvt_home': 'C:\\Users\\trade\\zvt-test-home'}
2021-01-03 00:09:09,666  INFO  MainThread  init config for zvt, current_config:{}
{'email_password': '',
 'email_username': '',
 'http_proxy': '127.0.0.1:1087',
 'https_proxy': '127.0.0.1:1087',
 'jq_password': '',
 'jq_username': '',
 'smtp_host': 'smtpdm.aliyun.com',
 'smtp_port': '80',
 'wechat_app_id': '',
 'wechat_app_secrect': ''}
2021-01-03 00:09:09,671  INFO  MainThread  current_config:{'jq_username': '', 'jq_password': '', 'http_proxy': '127.0.0.1:1087', 'https_proxy': '127.0.0.1:1087', 'smtp_host': 'smtpdm.aliyun.com', 'smtp_port': '80', 'email_username': '', 'email_password': '', 'wechat_app_id': '', 'wechat_app_secrect': ''}
DividendDetailRecorder:DividendDetail
DividendFinancingRecorder:DividendFinancing
RightsIssueDetailRecorder:RightsIssueDetail
SPODetailRecorder:SpoDetail
{'password': '', 'token': '', 'username': ''}
JqChinaEtfValuationRecorder:EtfValuation
JqChinaStockValuationRecorder:StockValuation
MarginTradingRecorder:MarginTrading
JqChinaStockRecorder:Stock
JqChinaEtfRecorder:Etf
JqChinaStockEtfPortfolioRecorder:EtfStock
StockTradeDayRecorder:StockTradeDay
JoinquantHkHolderRecorder:HkHolder
JoinquantIndexMoneyFlowRecorder:IndexMoneyFlow
JoinquantStockMoneyFlowRecorder:StockMoneyFlow
CrossMarketSummaryRecorder:CrossMarketSummary
MarginTradingSummaryRecorder:MarginTradingSummary
StockSummaryRecorder:StockSummary
JqChinaStockKdataRecorder:StockKdataCommon
JqChinaIndexKdataRecorder:IndexKdataCommon
ChinaStockBalanceSheetRecorder:BalanceSheet
ChinaStockCashFlowRecorder:CashFlowStatement
ChinaStockFinanceFactorRecorder:FinanceFactor
ChinaStockIncomeStatementRecorder:IncomeStatement
TopTenHolderRecorder:TopTenHolder
TopTenTradableHolderRecorder:TopTenTradableHolder
EastmoneyChinaBlockRecorder:Block
EastmoneyChinaBlockStockRecorder:BlockStock
ChinaETFListSpider:EtfStock
ChinaIndexListSpider:IndexStock
ExchangeChinaStockListRecorder:Stock
EastmoneyChinaStockListRecorder:Stock
EastmoneyChinaStockDetailRecorder:StockDetail
HolderTradingRecorder:HolderTrading
ManagerTradingRecorder:ManagerTrading
ChinaETFDayKdataRecorder:Etf1dKdata
ChinaIndexDayKdataRecorder:Index1dKdata
SinaChinaBlockRecorder:Block
SinaChinaBlockStockRecorder:BlockStock
SinaBlockMoneyFlowRecorder:BlockMoneyFlow
SinaStockMoneyFlowRecorder:StockMoneyFlow
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-005d93f24027> in <module>
----> 1 from zvt import *

AttributeError: module 'zvt' has no attribute 'AdjustType'

**Comment by foolcage** [comment]
拉一下最新代码，已修复。
