### ISSUE TITLE
合并doncat99/FinanceCenter中的一些对zvt的增强

### ISSUE THREAD

**Issue by zfsamzfsam** [zvtvz/zvt#132]
https://github.com/doncat99/FinanceCenter

**Comment by doncat99** [comment]
春节前我会整理放出一个更新版的zvt，FinanceCenter是基于jq的sdk做的，zvt的作者实现了http版的jq，能对pandas的版本解绑（这也是当初为什么我把zvt拆成两个项目的原因，跑分析的时候pandas 0.25确实不够用）。更新版的zvt merge了当前主线版本的最新代码，并且保留了美股分库功能。同时对代码逻辑做了一些修正，增加了Asyncio和multiprocessing的合并，加速数据下载。对应的，最近在融合proxy代理，Asyncio的能力太强，太容易被服务器封号。

**Comment by foolcage** [comment]
@doncat99 good,有需要的朋友可以参考下。

zvt核心还是保留目前的设计
- 不使用多线程，多进程，异步
- 扩展标的用插件实现

**Comment by doncat99** [comment]
https://github.com/doncat99/FinanceCenter

项目改进 (01 Mar 2021)：

数据库session句柄解耦
entity provider相关逻辑移除
数据库查询逻辑优化
异步框架支持 (实现需对函数进行async声明)
多进程逻辑重写，使用processes替代pool
增加代理池支持
增加baostock三方库支持
