### ISSUE TITLE
能不能把数据放一份google drive的？

### ISSUE THREAD

**Issue by svjack** [zvtvz/zvt#135]
如题，下数据不方便。

**Comment by svjack** [comment]
最好能在代码里添加下载功能。

**Comment by foolcage** [comment]
可以，打算维护一个共享数据列表

**Comment by foolcage** [comment]
最新的部分数据：
https://drive.google.com/drive/folders/17Bxijq-PHJYrLDpyvFAm5P6QyhKL-ahn?usp=sharing
