### ISSUE TITLE
应该只下载一套原始K线数据 和 价格调整表(或除权除息表),计算出前复权和后复权数据

### ISSUE THREAD

**Issue by zfsamzfsam** [zvtvz/zvt#137]
如题

**Comment by foolcage** [comment]
维护原始k线和复权因子数据并计算前后复权数据有好处（节省抓取时间），也有不利

- 增加复杂度，如果复权因子有问题，重算很麻烦
- 前复权数据经常需要重算
- 依赖其的指标需要重算
- 低级别的数据量非常大，计算量也非常大

所以目前的状态是

- 用后复权来做回测，好处在于历史数据不会随复权因子变动，自定义指标存储后不需要重算
- 用大一点的级别选股，再抓标的小级别的数据做实时策略（数据量较小）

你说的方案可以作为一个可选项，目前有根据 复权因子 计算前后复权价格的代码（在jq recorder里面），但没有专门提出来。

**Comment by zfsamzfsam** [comment]
https://www.akshare.xyz/zh_CN/latest/data/stock/stock.html

接口示例-前复权因子

	import akshare as ak
	qfq_factor_df = ak.stock_zh_a_daily(symbol="sz000002", adjust="qfq-factor")
	print(qfq_factor_df)


接口示例-后复权因子

	import akshare as ak
	hfq_factor_df = ak.stock_zh_a_daily(symbol="sz000002", adjust="hfq-factor")
	print(hfq_factor_df)

**Comment by doncat99** [comment]
空间换时间的问题。
