### ISSUE TITLE
支持literalquery功能用于debug

### ISSUE THREAD

**Issue by svjack** [zvtvz/zvt#142]
工程中使用query对象读取数据，应该有对应sql语句的debug
https://stackoverflow.com/questions/5631078/sqlalchemy-print-the-actual-query

**Comment by svjack** [comment]
另外有关recorder的run函数，能解释一下它的运行逻辑流程吗？
特别有关与entity数据更新的逻辑，我只看到用get_data读的地方，没有找到写的地方。
而且并不是所有的recorder在实例化时调用init_entities都能实例化出非空entities.
当然它的实例化也是通过调用get_data得到的。相当于用表维护类的attr，再用这些attr来更新维护表。
能简单解释一下你设计recorder并进行维护的思路吗？

**Comment by svjack** [comment]
另外，希望这个工程能出一个api文档，或者只对参数进行详尽叙述。

**Comment by foolcage** [comment]
> 另外，希望这个工程能出一个api文档，或者只对参数进行详尽叙述。

还有一些不太清晰的地方整理一下，会给一个比较完整的文档。
