### ISSUE TITLE
missing init_data_sample.py

### ISSUE THREAD

**Issue by Matx00** [zvtvz/zvt#147]
When I try to execute "python3 init_data_sample.py" it says "can't open file 'init_data_sample.py': [Errno 2] No such file or directory" even if I'm in the zit folder. In fact it is not present in the folder.

**Comment by foolcage** [comment]
@Matx00 
the english docs is too old for this project,I would update it asap.

**Comment by foolcage** [comment]
@Matx00 I updated some english docs, you could have a try.
