### ISSUE TITLE
在zvt_home目录中找不到config.json？

### ISSUE THREAD

**Issue by XianYuZhiWang** [zvtvz/zvt#152]
在zvt_home目录中找不到config.json，是不是按照这个
{'data_path': '/Users/xuanqi/zvt-home/data',
'domain_module': 'zvt.domain',
'email_password': '',
'email_username': '',
'http_proxy': '127.0.0.1:1087',
'https_proxy': '127.0.0.1:1087',
'jq_password': '',
'jq_username': '',
'log_path': '/Users/xuanqi/zvt-home/logs',
'smtp_host': 'smtpdm.aliyun.com',
'smtp_port': '80',
'ui_path': '/Users/xuanqi/zvt-home/ui',
'wechat_app_id': '',
'wechat_app_secrect': '',
'zvt_home': '/Users/xuanqi/zvt-home'}
改一下路径，自己建一个？

**Comment by foolcage** [comment]
理论上运行一次之后，就会自动创建，确认一下运行提示？

**Comment by XianYuZhiWang** [comment]
运行了还是空的，我自己创建了一个，OK了
