### ISSUE TITLE
Can GoldCrossFactor dump to local by pkl ? 

### ISSUE THREAD

**Issue by svjack** [zvtvz/zvt#154]
Can you try following code 
```python
        with open("day_gold_cross_factor.pkl", "wb") as f:
            pkl.dump(day_gold_cross_factor, f)
```
in init_selectors in MacdDayTrader ?

**Comment by foolcage** [comment]
the persistence of factor could be implemented in this way:

- define your factor domain, state(if need)
- set Factor arg need_persist
- implement sedes logic

the reference is:
https://github.com/zvtvz/zvt/blob/master/zvt/factors/zen/zen_factor.py

**Comment by svjack** [comment]
> the persistence of factor could be implemented in this way:
> 
> * define your factor domain, state(if need)
> * set Factor arg need_persist
> * implement sedes logic
> 
> the reference is:
> https://github.com/zvtvz/zvt/blob/master/zvt/factors/zen/zen_factor.py

Why can not support pickle ?
it report error like following:
PicklingError: Can't pickle ...: it's not the same object as...
describe in https://stackoverflow.com/questions/1412787/picklingerror-cant-pickle-class-decimal-decimal-its-not-the-same-object
Is this object construction have some complex import components ?

**Comment by foolcage** [comment]
@svjack 
yes.  most of the pandas/numpy data type.

**Comment by svjack** [comment]
> the persistence of factor could be implemented in this way:
> 
> * define your factor domain, state(if need)
> * set Factor arg need_persist
> * implement sedes logic
> 
> the reference is:
> https://github.com/zvtvz/zvt/blob/master/zvt/factors/zen/zen_factor.py

Dose mainly persist and load logic of Factor cls is defined in 
persist_factor and load_factor in Factor class, 
And all i can do should the help with them ?

**Comment by foolcage** [comment]
you're right.
You could try MaFactor with need_persist ,it's more simpler than ZenFacor(with State persistence).

**Comment by svjack** [comment]
> you're right.
> You could try MaFactor with need_persist ,it's more simpler than ZenFacor(with State persistence).

What should i do if i want to have a overview of all serialized factors in engine-map level ?

**Comment by foolcage** [comment]
> > you're right.
> > You could try MaFactor with need_persist ,it's more simpler than ZenFacor(with State persistence).
> 
> What should i do if i want to have a overview of all serialized factors in engine-map level ?

not registering them to context yet,maybe latter.

**Comment by svjack** [comment]
> > you're right.
> > You could try MaFactor with need_persist ,it's more simpler than ZenFacor(with State persistence).
> 
> What should i do if i want to have a overview of all serialized factors in engine-map level ?

This problem is similar when i use with some calculate logic which need data, 
i don’t want to try data not exists error and back to init or download them.
