### ISSUE TITLE
About the usage of trade_the_targets in Trader 

### ISSUE THREAD

**Issue by svjack** [zvtvz/zvt#155]
You not release the full code of MySoloTrader in your readme.
trade_the_targets define in Trader class seems only use in  MySoloTrader.
it construct some simple rules.
So do you have some more well example about this kind of methods ?
which can defeat the strategy made by MACD (and so on) or as your 
comments in run function of Trader , that define some logic in on_time
in every min run period well help to improve the exist strategy 
in a certain extent on backtest ?
Can you provide me some guide or example in truly chinese stock data ?

**Comment by foolcage** [comment]
basicly you could use any related domain to filter the targers in on_time.
I would give some examples latter.
