### ISSUE TITLE
[Bug] AttributeError: module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by fourdim** [zvtvz/zvt#158]
```
D:\anaconda3\envs\zvt\lib\site-packages\sqlalchemy\util\compat.py in <module>
    232 import time
    233 if win32 or jython:
--> 234     time_func = time.clock
    235 else:
    236     time_func = time.time

AttributeError: module 'time' has no attribute 'clock'
```
[Module 'time' has no attribute 'clock' in Python 3.8](https://stackoverflow.com/questions/58569361/attributeerror-module-time-has-no-attribute-clock-in-python-3-8)
From the Python 3.8 doc:

> The function time.clock() has been removed, after having been deprecated since Python 3.3: use time.perf_counter() or time.process_time() instead, depending on your requirements, to have well-defined behavior. (Contributed by Matthias Bussonnier in bpo-36895.)

Update the dependency `sqlalchemy` will resolve this issue.

**Comment by foolcage** [comment]
zvt has upgrade sqlalchemy and fixed
