### ISSUE TITLE
下载了历史数据替换后，运行FinanceFactor.record_data(codes=['000338'])报错

### ISSUE THREAD

**Issue by kungfutyf** [zvtvz/zvt#159]
使用pip方式在Ubuntu上安装的zvt
下载了历史数据替换后，运行FinanceFactor.record_data(codes=['000338'])报错
报错信息：
ERROR MainThread Missing column provided to 'parse_dates': 'pubDate'
是不是数据格式变了

**Comment by foolcage** [comment]
FinanceFactor数据抓的是东财的数据，由于缺少发布时间，需要从 聚宽去补，如果没配置聚宽账户的话会有这个错误。
这个错误不影响抓取，只是发布时间timestamp不准确，用的是公告日。

**Comment by kungfutyf** [comment]
> FinanceFactor数据抓的是东财的数据，由于缺少发布时间，需要从 聚宽去补，如果没配置聚宽账户的话会有这个错误。
> 这个错误不影响抓取，只是发布时间timestamp不准确，用的是公告日。

设置了聚宽数据账户还是报这个错误
