### ISSUE TITLE
希望能增加快报和预告的抓取

### ISSUE THREAD

**Issue by buginux** [zvtvz/zvt#16]
如题，希望能有快报以及预告的抓取功能。

**Comment by foolcage** [comment]
https://github.com/foolcage/fooltrader/blob/master/fooltrader/spiders/chinastock/stock_forecast_spider.py
https://github.com/foolcage/fooltrader/blob/master/fooltrader/spiders/chinastock/stock_finance_report_event_spider.py

有空的话,可以帮忙搬过来,字段follow zvt的规则即可
