### ISSUE TITLE
数据更新问题咨询

### ISSUE THREAD

**Issue by loserZhang** [zvtvz/zvt#160]
利用此接口更新数据报错Stock1dHfqKdata.record_data(provider='joinquant', sleeping_time=0, day_data=True)
ValueError: Missing column provided to 'parse_dates': 'date'
请问是什么原因？

**Comment by foolcage** [comment]
joinquant账号设置了吗？

**Comment by loserZhang** [comment]
没有设置，我设置试下，谢谢哈

**Comment by kungfutyf** [comment]
你设置了聚宽帐号还有这个错误吗，我设置以后问题还在

**Comment by foolcage** [comment]
最新版本优化了错误提示，请使用最新版本。
