### ISSUE TITLE
获取数据后，在使用VolumeUpMaFactor函数的时候引发异常

### ISSUE THREAD

**Issue by double-cool** [zvtvz/zvt#161]
您好，请问下我在获取数据后，在使用VolumeUpMaFactor函数的时候引发异常，报(sqlite3.OperationalError) too many SQL variables [SQL: 'SELECT stock_1d_hfq_kdata.timestamp,。我有将max_allowed_packet改成500M但还是报这个异常，请问是什么缘故呢？

**Comment by foolcage** [comment]
参考:
https://github.com/zvtvz/zvt/issues/79

**Comment by double-cool** [comment]
好的，谢谢
