### ISSUE TITLE
重构recorder

### ISSUE THREAD

**Issue by foolcage** [zvtvz/zvt#17]
目标:

- 更通用
- 更易扩展

**Comment by buginux** [comment]
有何思路？

**Comment by foolcage** [comment]
- api wrapper合到base class里面
- 对生成domain和更新domain的操作做更好的分类
- 封装selenium常用操作，封装需要登录的网站

**Comment by foolcage** [comment]
已完成。
@buginux 重构后，etf的recorder可能需要你重新弄一下，有可能有问题。
