### ISSUE TITLE
使用0.9.4版本的zvt命令报错

### ISSUE THREAD

**Issue by superjcd** [zvtvz/zvt#175]
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: trader_info.kdata_adjust_type
[SQL: SELECT trader_info.id AS trader_info_id, trader_info.entity_id AS trader_info_entity_id, trader_info.timestamp AS trader_info_timestamp, trader_info.trader_name AS trader_info_trader_name, trader_info.entity_type AS trader_info_entity_type, trader_info.start_timestamp AS trader_info_start_timestamp, trader_info.end_timestamp AS trader_info_end_timestamp, trader_info.provider AS trader_info_provider, trader_info.level AS trader_info_level, trader_info.real_time AS trader_info_real_time, trader_info.kdata_use_begin_time AS trader_info_kdata_use_begin_time, trader_info.kdata_adjust_type AS trader_info_kdata_adjust_type
FROM trader_info ORDER BY trader_info.timestamp ASC]

应该是缺少字段吧~

**Comment by foolcage** [comment]
在你的用户目录zvt-home/data里面删掉zvt_trader_info.db，重跑就好。
