### ISSUE TITLE
eastmoney无法抓取报表

### ISSUE THREAD

**Issue by weshky** [zvtvz/zvt#177]
使用exampe中的eastmoney抓取stock list和meta成功，但是抓取东财的报表貌似没有执行

Stock registered recorders:{'joinquant': <class 'zvt.recorders.joinquant.meta.china_stock_meta_recorder.JqChinaStockRecorder'>, 'exchange': <class 'zvt.recorders.exchange.china_stock_list_spider.ExchangeChinaStockListRecorder'>, 'eastmoney': <class 'zvt.recorders.eastmoney.meta.china_stock_meta_recorder.EastmoneyChinaStockListRecorder'>}
Empty DataFrame
Columns: [code, name, list_date]
Index: []
Empty DataFrame
Columns: [code, name, list_date]
Index: []
FinanceFactor registered recorders:{'eastmoney': <class 'zvt.recorders.eastmoney.finance.china_stock_finance_factor_recorder.ChinaStockFinanceFactorRecorder'>}
BalanceSheet registered recorders:{'eastmoney': <class 'zvt.recorders.eastmoney.finance.china_stock_balance_sheet_recorder.ChinaStockBalanceSheetRecorder'>}
IncomeStatement registered recorders:{'eastmoney': <class 'zvt.recorders.eastmoney.finance.china_stock_income_statement_recorder.ChinaStockIncomeStatementRecorder'>}
CashFlowStatement registered recorders:{'eastmoney': <class 'zvt.recorders.eastmoney.finance.china_stock_cash_flow_recorder.ChinaStockCashFlowRecorder'>}

Output completed (5 sec consumed) - Normal Termination

**Comment by foolcage** [comment]
@weshky 没有看到错误日志？
最好按readme里面的步骤来跑。

**Comment by weshky** [comment]
就是用readme里面的步骤，下载了百度盘的eastmoney的数据，更新stock列表和detail正常，报表就无法获取了

**Comment by foolcage** [comment]
@weshky 把joinquant的数据也下载了，现在stock列表的数据用的joinquant的，抓报表需要遍历stock去抓。

**Comment by weshky** [comment]
@foolcage OK,非常感谢,是否有可能在未来版本中允许选择使用哪个源的stock列表呢?

**Comment by foolcage** [comment]
> @foolcage OK,非常感谢,是否有可能在未来版本中允许选择使用哪个源的stock列表呢?

有些地方entity_provider没有参数话，可以自己改。
大部分地方通过传参都可以。
