### ISSUE TITLE
I cant see how to start the program

### ISSUE THREAD

**Issue by MZULALI** [zvtvz/zvt#178]
Sorry I dont speak Chinese, but I have a translator. I can translate the new README but im not sure what to do

What do I put into IPython? when I run main.py, I can open 127.0.0.1, but there is nothing.

Can you help me?

thank you

**Comment by foolcage** [comment]
@MZULALI you could download the history data from google drive and unzip them to ~/zvt-home/data

In fact, just some core concepts need to know and you could use all of them...I would complete docs latter.

**Comment by MZULALI** [comment]
I have done that.
![zvvt](https://user-images.githubusercontent.com/75442794/128417891-86c1ebf5-ed68-482b-8388-abbf64425c36.png)

this is what I mean. When I load main.py, I dont get any options. How do I fix? I am still new to programming, sorry.

Thank you

**Comment by foolcage** [comment]
1)you could select entity and the factor on it

2)you could run the traders in examples, after that, you could see the performance of the trader in the UI.
in this case, the entity and factor is related to the trader.

3) in any case, you could select [related/all data to] data to show in the sub grath.

**Comment by foolcage** [comment]
@MZULALI I updated some english docs, you could have a try.
