### ISSUE TITLE
下载了历史数据替换后，更新数据报错

### ISSUE THREAD

**Issue by epoches** [zvtvz/zvt#184]
from zvt.domain import *
from tests.context import init_test_context
init_test_context()
def getdata():
    Stock.record_data(provider='joinquant')
在测试目录添加文件，提示：
JoinquantIndexMoneyFlowRecorder:IndexMoneyFlow
{'password': '', 'token': 'error: mob/pwd不能为空', 'username': ''}
目录放到zvt samples下面就好了。
建议给个例子，不然新手不知道怎么更新。
还有技术指标，没看到具体的指标说明。这里面注释太少了，不是每个人都有时间研究源码的。大多数是对不感兴趣的会用就行。
例如怎么使用聚宽 jqdatasdk和zvt共用。
包括providers有具体有哪些，如何能最快的更新到最新。
我用Stock1dHfqKdata.record_data(provider = 'joinquant', sleeping_time = 1) 速度会快些，用jqdatasdk是否有更快的方法。
这些很影响改策略的速度，只有有人用才会有人开发啊，用的人是基石。

**Comment by foolcage** [comment]
@epoches 更新了部分文档，建议step by step走一遍。

**Comment by hxsam** [comment]
哪里有step by step? 
zvt\ui\apps\factor_app.py#L16
# from zvt.domain import TraderInfo 这个报找不到 ，改成
from zvt.trader.trader_schemas import AccountStats, Order, TraderInfo, Position

master 跑起来了，tader_info 是空的。

**Comment by foolcage** [comment]
@hxsam 可以跟着英文文档走一遍。由于不少功能还在快速开发中，无法保证兼容性。
