### ISSUE TITLE
NameError: name 'get_finance_factor' is not defined

### ISSUE THREAD

**Issue by todaygood** [zvtvz/zvt#196]
Hi， 

I ran the example :
In [12]: from zvt.domain import *
In [13]: df = get_finance_factor(entity_id='stock_sz_000338',columns=FinanceFactor.important_cols())

In [14]: df.tail()
but throw out "NameError: name 'get_finance_factor' is not defined" ,  My zvt code is zvt master.

**Comment by foolcage** [comment]
现在统一用{schema}.query_data来做。

>>> from zvt.domain import *
>>> FinanceFactor.record_data(entity_id='stock_sz_000338')
>>> df = FinanceFactor(entity_id='stock_sz_000338',columns=FinanceFactor.important_cols())


`
