### ISSUE TITLE
东财财务数据BUG

### ISSUE THREAD

**Issue by wisfern** [zvtvz/zvt#20]
东财数据下的财务数据，新的中报，年报，有如下的数据：
![图片](https://user-images.githubusercontent.com/1068193/63237045-ed9c1400-c272-11e9-9c44-9d93727777e0.png)

没有这个数据，还是可以查询出来，不知道是不是BUG。

**Comment by foolcage** [comment]
@wisfern 
是个历史问题,一开始考虑可能需要不同的provider放在同一张表里.
provider目前是冗余字段,可以忽略,因为不同的provider肯定在不同的库里.

**Comment by foeyes** [comment]
那如果一张表 有不同的provider提供数据怎么定义？




佛说:"不可说，不可说，一说便是错！"
在2019年08月19日 12:47，foolcage 写道：

@wisfern
是个历史问题,一开始考虑可能需要不同的provider放在同一张表里.
provider目前是冗余字段,可以忽略,因为不同的provider肯定在不同的库里.

**Comment by foolcage** [comment]
@foeyes 字段来自不同的provider,你需要合并起来？这种情况还是指定一个provider就好，recorder里面在on_finish里面做合并来自其他provider的字段，目前有些数据就是这样处理的。

不同provider的相同类型的数据，不推荐放在一张表里面，provider目前主要是用来做最外层的数据路由的。
