### ISSUE TITLE
东财数据无法获取

### ISSUE THREAD

**Issue by paradiseHIT** [zvtvz/zvt#200]
>>> BalanceSheet.record_data(code='000338')
BalanceSheet registered recorders:{'eastmoney': <class 'zvt.recorders.eastmoney.finance.eastmoney_balance_sheet_recorder.ChinaStockBalanceSheetRecorder'>}
2022-06-04 19:33:13,020  INFO  MainThread  joinquant query count:Empty DataFrame
Columns: [error: token无效，请重新获取]
Index: []

**Comment by foolcage** [comment]
这里是用joinquant来补全发布时间，没有joiquant账号的话，timestamp默认用报告期时间。
其他字段不影响使用。

**Comment by paradiseHIT** [comment]
joiquant账号如何获取，还是joinquant账号？有笔误？

另外要配置的话有文档没有，我参考README没看到，不知道是不是漏了哪一步？

**Comment by foolcage** [comment]
https://www.joinquant.com/default/index/sdk
可以申请免费试用。
配置~/zvt-home/config.json:

jq_username 聚宽数据用户名
jq_password 聚宽数据密码
smtp_host 邮件服务器host
smtp_port 邮件服务器端口
email_username smtp邮箱账户
email_password smtp邮箱密码
wechat_app_id
wechat_app_secrect

其他的数据源不需要配置。

大部分用provider em即可。

**Comment by foolcage** [comment]
https://www.joinquant.com/default/index/sdk
可以申请免费试用。
配置~/zvt-home/config.json:

jq_username 聚宽数据用户名
jq_password 聚宽数据密码
smtp_host 邮件服务器host
smtp_port 邮件服务器端口
email_username smtp邮箱账户
email_password smtp邮箱密码
wechat_app_id
wechat_app_secrect

其他的数据源不需要配置。

大部分用provider em即可。
