### ISSUE TITLE
执行财务因子相关报错

### ISSUE THREAD

**Issue by benkang-chen** [zvtvz/zvt#203]
执行    FinanceFactor.record_data(code='000338')
报
2022-11-30 17:28:54,194  INFO  MainThread  joinquant query count:Empty DataFrame
Columns: [error: token无效，请重新获取]
Index: []
请问什么原因

**Comment by foolcage** [comment]
这里是调用joinquant api来补全 发布日期 数据，可以忽略。
默认用的报告期。

**Comment by host527** [comment]
最新的0.13.2仍存在这个问题，财务因子无法获取到，是个empty df
