### ISSUE TITLE
哪位热心人士提供一份可以运行环境的PIP LIST？

### ISSUE THREAD

**Issue by JulianZhang** [zvtvz/zvt#211]
现在有好几个问题，其实都是没有使用正确的库版本造成的，如果谁已经正确运行了，能否提供一份PIP LIST，以供新人参考

如下几个问题都是依赖版本不正确造成的

https://github.com/zvtvz/zvt/issues/210
https://github.com/zvtvz/zvt/issues/202

**Comment by huakuiiii** [comment]
[requirements.txt](https://github.com/zvtvz/zvt/files/14433791/requirements.txt)

**Comment by ivandon15** [comment]
建议用conda或者mamba重新建一个环境，再使用python3 -m pip install -U zvt是没问题的
