### ISSUE TITLE
运行init_tag_system.py报 No module named 'zvt.tag.tag_service'

### ISSUE THREAD

**Issue by HogwartsRico** [zvtvz/zvt#219]
先执行了 `python3 -m pip install -U zvt`   安装成功
然后按照readme操作，
![image](https://github.com/user-attachments/assets/e10d6024-2206-47b2-a2ad-3d5b2f0fda02)
运行init_tag_system.py报 No module named 'zvt.tag.tag_service'
![image](https://github.com/user-attachments/assets/9db36410-4d33-47eb-ad92-5d61ba11dacf)

**Comment by foolcage** [comment]
这个跟运行目录有关，源码运行的话保证PYTHONPATH设置正确
