### ISSUE TITLE
开发计划

### ISSUE THREAD

**Issue by foolcage** [zvtvz/zvt#22]
- [x] 聚宽数据补全
- [x] 统一的主图，附图，标记绘图
- [x] 多级别交易的例子
- [x] 优化实时行情的演示
- [x] 优化实时数据的计算

**Comment by buginux** [comment]
东财数据还包括哪些？

**Comment by foolcage** [comment]
> 东财数据还包括哪些？

http://m.data.eastmoney.com/

这里面能看到的都能抓取，有兴趣的话可以搞一下。

**Comment by ohyeah521** [comment]
https://tushare.pro/

这个网站的数据质量不错

**Comment by zhangshoug** [comment]
https://github.com/QUANTAXIS/QUANTAXIS使用pytdx通达信行情，获取数据速度很快。

**Comment by zhangshoug** [comment]
楼上说的tusharepro,也很好;机器上的https://github.com/moyuanz/DevilYuan
已经将tusharepro的数据下载在本地了，tick数据也有

**Comment by foolcage** [comment]
> 楼上说的tusharepro,也很好;机器上的https://github.com/moyuanz/DevilYuan
> 已经将tusharepro的数据下载在本地了，tick数据也有

项目支持多provider,即一个shcema里面可以有多个providers,后面会考虑添加pytdx和tusharepro支持。

**Comment by zhangshoug** [comment]
添加pytdx支持的时候，可否考虑直接调用QA和tusharepro，可否考虑直接读取DY的本地数据库，不重复去下载

**Comment by foolcage** [comment]
> 添加pytdx支持的时候，可否考虑直接调用QA和tusharepro，可否考虑直接读取DY的本地数据库，不重复去下载

zvt数据记录是增量的,不会重复下载。
DY是啥？

**Comment by zhangshoug** [comment]
DY就是https://github.com/moyuanz/DevilYuan 
这个量化框架，我目前当成下载数据的工具用了.
