### ISSUE TITLE
[bug] Module not found in starting code

### ISSUE THREAD

**Issue by PrinceP** [zvtvz/zvt#30]
git clone https://github.com/zvtvz/zvt.git

    from zvt.apps import trader_app
ModuleNotFoundError: No module named 'zvt.apps'

**Comment by foolcage** [comment]
@PrinceP 

1)please make sure add zvt to PYTHONPATH or system PATH if you want to use zvt in your python env

2)it's a good choice to  imoport the project to pycharm for developing and testing
