### ISSUE TITLE
对于报表的调整如何处理

### ISSUE THREAD

**Issue by buginux** [zvtvz/zvt#32]
有些报表的数据会存在调整，比如万华化学本年三季报就对去年的三季节进行了调整，这种情况下程序应该是无感知的，有没有办法让程序去进行更新？

**Comment by foolcage** [comment]
如果有接口能够知道有调整，可以设置recorder为force_update,在抓完后，去抓有调整的。
不够这个只有理论上的意义，因为发生了就是发生了，回测的环境已经不真实。
