### ISSUE TITLE
示例里重复运行  t = MyMaTrader， t.run,会报错

### ISSUE THREAD

**Issue by joyjarod163** [zvtvz/zvt#35]
t = MyMaTrader(codes=['000338'], level=IntervalLevel.LEVEL_1DAY, start_timestamp='2019-01-01',
    ...:    ...:                end_timestamp='2019-06-30', trader_name='000338_ma_trader')
InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Origi
nal exception was: (sqlite3.IntegrityError) UNIQUE constraint failed: sim_account.id

**Comment by foolcage** [comment]
重复运行似乎没啥意义，暂时不支持。
