### ISSUE TITLE
记录tick数据报错

### ISSUE THREAD

**Issue by manstiilin** [zvtvz/zvt#36]
IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: coin_tick_kdata.id [SQL: 'INSERT INTO coin_tick_kdata (id, entity_id, timestamp, provider, code, name, level, "order", price, volume, turnover, direction, order_type) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: (('coin_binance_BTC/USDT_2019-12-26T14:51:31.552', 'coin_binance_BTC/USDT', '2019-12-26 14:51:31.552000', 'ccxt', 'BTC/USDT', 'BTC/USDT', 'tick', None, 7215.15, 0.161462, 1164.9725492999999, 'sell', None), ('coin_binance_BTC/USDT_2019-12-26T14:51:31.552_1', 'coin_binance_BTC/USDT', '2019-12-26 14:51:31.552000', 'ccxt', 'BTC/USDT', 'BTC/USDT', 'tick', None, 7215.91, 0.041979, 302.91668589, 'buy', None), ('coin_binance_BTC/USDT_2019-12-26T14:51:31.552_2', 'coin_binance_BTC/USDT', '2019-12-26 14:51:31.552000', 'ccxt', 'BTC/USDT', 'BTC/USDT', 'tick', None, 7215.94, 0.251136, 1812.18230784, 'buy', None), ('coin_binance_BTC/USDT_2019-12-26T14:51:31.961', 'coin_binance_BTC/USDT', '2019-12-26 14:51:31.961000', 'ccxt', 'BTC/USDT', 'BTC/USDT', 'tick', None, 7215.91, 0.001551, 11.19187641, 'buy', None), ('coin_binance_BTC/USDT_2019-12-26T14:51:34.138', 'coin_binance_BTC/USDT', '2019-12-26 14:51:34.138000', 'ccxt', 'BTC/USDT', 'BTC/USDT', 'tick', None, 7215.43, 0.088969, 641.94959167, 'buy', None), ('coin_binance_BTC/USDT_2019-12-26T14:51:36.413', 'coin_binance_BTC/USDT', '2019-12-26 14:51:36.413000', 'ccxt', 'BTC/USDT', 'BTC/USDT', 'tick', None, 7214.91, 0.142148, 1025.58502668, 'sell', None), ('coin_binance_BTC/USDT_2019-12-26T14:51:36.413_3', 'coin_binance_BTC/USDT', '2019-12-26 14:51:36.413000', 'ccxt', 'BTC/USDT', 'BTC/USDT', 'tick', None, 7214.9, 0.24856, 1793.335544, 'sell', None), ('coin_binance_BTC/USDT_2019-12-26T14:51:36.413_4', 'coin_binance_BTC/USDT', '2019-12-26 14:51:36.413000', 'ccxt', 'BTC/USDT', 'BTC/USDT', 'tick', None, 7214.88, 0.109292, 788.52866496, 'sell', None), ('coin_binance_BTC/USDT_2019-12-26T14:51:37.382', 'coin_binance_BTC/USDT', '2019-12-26 14:51:37.382000', 'ccxt', 'BTC/USDT', 'BTC/USDT', 'tick', None, 7215.37, 0.711563, 5134.190323309999, 'buy', None))] (Background on this error at: http://sqlalche.me/e/gkpj)

相同的时间点，多个数据，重新生成的id跟数据库已经存储的重复。

**Comment by foolcage** [comment]
最新版本已修复，如果重复，会在后面加一个uuid
