### ISSUE TITLE
少文档少说明，不便学习使用

### ISSUE THREAD

**Issue by zhangshoug** [zvtvz/zvt#39]
不知数据都支持什么级别的，分钟和tick的回测支持么。

目前使用过几个聚宽、米筐等，觉得易用性还是聚宽好一点，米筐的网站使用分钟数据回测也可以。
但米筐开源的rqalpha在本地没有分钟或tick数据，也没有换手率数据，本地写策略不甚方便。

另外，策略不止使用标的的K线数据；使用了持仓数据，不知ZVT是否有类似聚宽、米筐的context对象供写策略时调用持仓信息.

回测和模拟交易是否支持bar的开盘价撮合。

聚宽的回测支持开盘价撮合，模拟交易在09:27就发交易信号了，实盘跟单很是方便.

**Comment by foolcage** [comment]
@zhangshoug 
1)所有级别都支持，包括tick,可以查看IntervalLevel的定义
2)一切都是本地化的，目前数据支持已经较多，扩展也比较快
3)有持仓信息 
4)开盘价撮合还不支持
5)实盘跟单后面会做，其实很容易支持了，但还没写文档和例子

文档很快会完善

**Comment by zhangshoug** [comment]
有tick和分钟级别，就不用支持bar的开盘价撮合了．全天第一个tick产生后就发单就可以了

**Comment by manstiilin** [comment]
感觉这是个被严重低估的项目，希望能快点完善文档。

**Comment by foolcage** [comment]
文档相关问题请统一到：https://github.com/zvtvz/zvt/issues/43
