### ISSUE TITLE
增加 ETF 数据抓取

### ISSUE THREAD

**Issue by buginux** [zvtvz/zvt#4]
目前代码中没有 ETF 数据的抓取，此 issue 为该功能的相关讨论。

**Comment by buginux** [comment]
群主在 QQ 群中的回答

> 自己搞etf类数据的话
> 建议存指数 指数里面加一类StockCategory=etf
>
> 这样的好处是:
> 1. 可以用get_securities直接读取指数数据
> 2. 可以使用统一的get_securities_in_block函数(今天提交会包含这个函数)
> 3. etf行情数据可以开一个StoreCategory来存取

**Comment by foolcage** [comment]
get_securities_in_blocks已在最新代码中添加,可跑一下测试的例子.

**Comment by buginux** [comment]
获取 ETF 成分股貌似没有直接的方法。

1. 上交所有直接提供成分股，但是请求里面用的不是 code 而是 type，这个 type 我还没有找到获取方式。
2. 深交所没有提供成分股信息，只能自己根据对应 ETF 跟踪的指数来查询成分股。

**Comment by buginux** [comment]
网站上找不到 ETF 的开高收低行情下载（JQ上可以），在网易和新浪上面似乎只能找到基金净值的历史数据，也就是只有 close 的历史数据。

**Comment by foolcage** [comment]
@buginux 可以用jq的数据来做,接下来估计会把整个jq 的数据都本地化,可以参与进来.
毕竟其他网站的数据不能保证一直可用.目前的想法是:
**只有JQ拿不到的数据和一些自己确实很喜欢的数据会去爬**
**东财的数据我自己会做一个中转数据源**

**Comment by buginux** [comment]
@foolcage 使用 JQ 的问题在于，他们的数据是需要付费的，试用的话也只有一年。如果以 JQ 为主的话，这个项目会不会变得依赖性太重。

**Comment by foolcage** [comment]
@buginux 嗯 这个会做一个平衡 我个人可能会以JQ为主 因为精力确实有限.不过整个数据是支持多provider,做多provider目的是为了项目数据的一致性和长期可用,即使JQ不提供数据服务了,也不影响项目使用.

东财的数据比较全,我目前在做数据的中转,也能满足大部分人的要求
其他provider大家可以一起来完善

**Comment by foolcage** [comment]
#8 
ETF日线数据的存储位置待商榷,看是否存在Index1DKData里面.

**Comment by buginux** [comment]
已完成，关闭之。
