### ISSUE TITLE
里面的example的provider修改其他会报错

### ISSUE THREAD

**Issue by 1148270327** [zvtvz/zvt#41]
![image](https://user-images.githubusercontent.com/22876908/72312263-8f108000-36c2-11ea-9850-a80ee71e5dbd.png)
首先改写作者的分享。我修改了相关provider执行上面的文件，一直报错没数据哎。而聚宽我没去注册，只想本地学习下，用下好的数据。求教

**Comment by foolcage** [comment]
目前不支持eastmoney的k线数据，各个provider的历史数据晚一点我会做一个表格～可以直接下载使用

**Comment by zhangshoug** [comment]
聚宽的试用数据下载有条数限制，建议默认provider使用tusharePro,pytdx等

**Comment by ohyeah521** [comment]
建议使用http://baostock.com/baostock/index.php/%E9%A6%96%E9%A1%B5 数据源，聚宽和tusharepro都很恶心
