### ISSUE TITLE
AttributeError: module 'zvt' has no attribute 'domain'

### ISSUE THREAD

**Issue by ZuoVJ** [zvtvz/zvt#42]
![image](https://user-images.githubusercontent.com/10162866/72595091-09036c00-3944-11ea-8b87-52b0088da973.png)

**Comment by foolcage** [comment]
是安装使用？还是源码使用？
如果是源码，先确认项目根目录加到PYTHONPATH里面。

**Comment by foolcage** [comment]
保证环境配置正确，最新版本无该问题
