### ISSUE TITLE
基于EastmoneyMoreDataRecorder的记录问题

### ISSUE THREAD

**Issue by foeyes** [zvtvz/zvt#47]
class EastmoneyMoreDataRecorder(BaseEastmoneyRecorder, TimeSeriesDataRecorder):
    def evaluate_start_end_size_timestamps(self, entity):
       。。。。。
        if latest_record:
            remote_record = self.get_remote_latest_record(entity)
            if not remote_record or (
                    latest_record[0].id == remote_record.id):
                return None, None, 0, None
            else:
                return None, None, 10, None

        return None, None, 1000, None
貌似evaluate_start_end_size_timestamps这里的处理有问题，如果第一次获取数据超过1000只能获取最新的1000条，增量更新时超过10条将只能获取最新10条。

**Comment by foolcage** [comment]
理论上问题不大，因为是财务数据，一年最多4条，1000/4=250年。
第一次更新后，如果你10/4=2.5年后再更新会有问题。

**Comment by foeyes** [comment]
原来只是用于财务数据采集啊。我以为还可以用于其他  那类名是不是可以改一下更清晰些或者注释下  哈哈哈




佛说:"不可说，不可说，一说便是错！"
在2020年01月30日 13:11，foolcage 写道：

理论上问题不大，因为是财务数据，一年最多4条，1000/4=250年。
第一次更新后，如果你10/4=2.5年后再更新会有问题。

**Comment by foolcage** [comment]
> 原来只是用于财务数据采集啊。我以为还可以用于其他 那类名是不是可以改一下更清晰些或者注释下 哈哈哈 佛说:"不可说，不可说，一说便是错！" 在2020年01月30日 13:11，foolcage 写道： 理论上问题不大，因为是财务数据，一年最多4条，1000/4=250年。 第一次更新后，如果你10/4=2.5年后再更新会有问题。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

目前继承该类的都是些比较低频的数据。

**Comment by foeyes** [comment]
好哒
