### ISSUE TITLE
选股推送,有需要的把邮箱pr一下

### ISSUE THREAD

**Issue by foolcage** [zvtvz/zvt#48]
![pick-stock](https://user-images.githubusercontent.com/1160499/74249262-dfabe500-4d23-11ea-89b2-ebc04019e86c.png)

![core](https://user-images.githubusercontent.com/1160499/74251283-dec88280-4d26-11ea-9fbe-5610252e8218.jpg)

目前自己跑了一些定时任务，定时推送符合条件的个股，需要的可以把自己的邮箱pr到以下目录：
https://github.com/zvtvz/zvt/tree/master/examples/reports

比如：
[中国核心资产](https://github.com/zvtvz/zvt/blob/master/examples/reports/report_core_compay.py)

[放量突破年线](https://github.com/zvtvz/zvt/blob/master/examples/reports/report_vol_up250.py)

pr的格式

```
# 加上你的邮箱
email_action.send_message(["5533061@qq.com","you@qq.com"], f'{target_date} 放量突破年线选股结果', msg)
```
即使选了相同的股，不同的人操作还是千差万别，所以，公开也没什么。
这里面的选股器是可以直接回测的，回测的通知信号也可以发送。

![me](https://user-images.githubusercontent.com/1160499/74312168-234a3180-4dac-11ea-9b41-85317e0faa94.jpg)

基本上个人的操作都是这两个选股器推送的结果，加上一点其他分析。

这不算荐股，利用zvt的factor可以组合各种算法，这里只是抛砖引玉而已，有兴趣交流的可以加我微信foolcage，注明自己的github用户名。

**Comment by manstiilin** [comment]
https://github.com/zvtvz/zvt/pull/50 谢谢

**Comment by yinianfangxia** [comment]
对于不熟悉pr的，参考
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests

快速命令:

在你fork的repo中,先同步
```
git remote add upstream https://github.com/zvtvz/zvt.git
git fetch upstream
git checkout master
git merge upstream/master
```
新开一个branch来做PR
```
git checkout -b patch-1
```
改好代码，push上去

到主项目create pull request即可

**Comment by foolcage** [comment]
使用东财app的，可以使用
https://github.com/zvtvz/eastmoneypy

把定时任务选中的标的推送到手机上.两个report例子已经添加相应代码

**Comment by foolcage** [comment]
选股日期之前有个bug，导致推送的日期总是不变，已修正。
放量突破年线这个用好，配合一点板块资金流，够用了。

**Comment by webnet918** [comment]
请问，可以筛选长年连续分红的公司吗？

**Comment by foolcage** [comment]
> 请问，可以筛选长年连续分红的公司吗？

用DividendFinancing数据参考例子来做，应该不难。
