### ISSUE TITLE
建议不要把A股代码和其他交易代码放到一起，否则就走了vnpy的老路

### ISSUE THREAD

**Issue by ohyeah521** [zvtvz/zvt#65]
希望把A股代码和数字货币等其他交易代码独立出来，这样新人在拿到代码后可以快速熟悉和参与开发自己要进行的交易代码，免得代码过于复杂后增加开发人员和维护人员的负担，不利于后期维护

**Comment by foolcage** [comment]
不错的建议

**Comment by ohyeah521** [comment]
昨天同步代码，发现多了好多数字货币的东西，代码看起来杂乱无章，都弄到一起后，不懂的其交易逻辑的人很难理解代码中的含义，阅读代码比较困难，而且开发者修改了其中部分代码，引入后可能造成其他交易品种出错。

**Comment by foolcage** [comment]
请先看文档，了解entity定义的统一性。也可能是你的内心杂乱无章。
