### ISSUE TITLE
可否更新一份最新的data数据

### ISSUE THREAD

**Issue by wisfern** [zvtvz/zvt#69]
我更新了最新的数据之后，发现东财的年报数据更新不全， 目前我手上的数据量，不到800只股票有19年的年报，一季度的数据量更少。
看了数据更新日志，不少获取 不到数据的。
大概类似这样的
could not get data for nested_fields:['GaoGuanZengJianList']

因此，我想问一下，能否提供一下最新的db数据放到百度盘，提供下载？

**Comment by foolcage** [comment]
没问题，晚点整理下

**Comment by wisfern** [comment]
谢谢，很期待

**Comment by foolcage** [comment]
最新的数据下载链接，包括日线/周线 前/后复权数据，东财财务数据，大股东持仓，高管增减持，分红送股

链接: https://pan.baidu.com/s/16BZOkEY2PBTkixJgzls66w 提取码: gfxc

请使用最新代码。

pypi发版会晚一点。

**Comment by foolcage** [comment]
please use 0.8.0 and the latest data
