### ISSUE TITLE
jq的k线数据记录问题

### ISSUE THREAD

**Issue by yinianfangxia** [zvtvz/zvt#72]
目前是只保存前复权数据，当数据变动时，在on_finish_entity里面把之前的数据按最新的factor计算，这里有一个问题，on_finish_entity可能在全部抓完后才回调，可能出现用最后entity的factor计算其他entity的错误。

- 建议计算逻辑直接放在抓取后

- 建议保存后复权数据，因为后面factor的计算如果用qfq,当数据变动，也需要重新计算，有时作回测hfq是个好选择

**Comment by foolcage** [comment]
确实有这个问题，下个版本会修复并提供后复权数据

**Comment by foolcage** [comment]
最新代码已修复，并提供后复权数据。

**Comment by wisfern** [comment]
我想了解一下，怎么不考虑保存一下复权因子和原始的ohlc，然后在取数据的时候，根据参数来确定前后复权数据的变换。
这样保存的数据占用的空间会小一些，如果是分钟级的话，减少的空间占用会比较可观。

**Comment by foolcage** [comment]
@wisfern 时间和空间是个取舍，由于项目中经常需要全市场的快速回测，每次取数据“重新计算”会变得不现实。
分钟级别的可以根据需要下载，一般不太需要全部数据。
