### ISSUE TITLE
[data]沪深港股通持股明细

### ISSUE THREAD

**Issue by wisfern** [zvtvz/zvt#87]
类似tushare中的数据定义
![图片](https://user-images.githubusercontent.com/1068193/89015082-1533a180-d349-11ea-8438-44a20bf7bcac.png)

**Comment by scanfyu** [comment]
A new plugin for zvt, see https://github.com/scanfyu/zvt-tushare.

**Comment by foolcage** [comment]
@scanfyu 
建议实现步骤
1)复用Stock entity，只是添加tushare provider
加上这句:
```
register_schema(providers=['joinquant', 'eastmoney', 'exchange', 'sina','tushare'], db_name='stock_meta',
                schema_base=StockMetaBase)
```
这样其他人安装zvt-tushare,自动就可以tushare的能力，其他模块直接复用
2）其他数据属于entity event
参考
https://zvtvz.github.io/zvt/#/data_extending
https://github.com/zvtvz/zvt-ccxt

**Comment by foolcage** [comment]
@scanfyu 
>这里我是在domain下边新建一个meta并继承stock_meta还是说直接在domain下建立stock_meta并继承啊？

两种方案
1）
可以不重新建meta,只是在domain的__init__里面执行一下：
```
register_schema(providers=['tushare'], db_name='stock_meta',
                schema_base=StockMetaBase)
```

这个函数这样用暂时有点问题(索引不能重建)，我晚点修复一下

2)自己新定义一种entity

一些特性的复用会有问题，比如StockTrader,StockKdata之类。

可以等我把register_schema做成幂等再弄。。
