### ISSUE TITLE
[data] tushare provider support

### ISSUE THREAD

**Issue by doncat99** [zvtvz/zvt#98]
这个项目scanfyu/zvt-tushare感觉没做完，我还是没懂怎么能加tushare provider上去，因为jq有些数据缺失，如果用tushare能补上去就好了。

之前也看了issues上面大概介绍了步骤，但还是说得有点浅，我想在zvt项目上直接加provider，而不是新的项目做patch。

**Comment by chforest** [comment]
我加个试试

**Comment by foolcage** [comment]
@chforest    独立项目出来做比较好。
后面打算是 zvt 只保留抽象层，尽量减少依赖。
最近计划把期货弄一下。zvt-future, 其他的可以参考一下。
